version: "3.2"

services:
  db:
    image: postgres:12.3
    container_name: Nimble
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=Nimble_development
    ports:
      - "5432:5432"
