name: Apply API variant

on: push

jobs:
  standard_api_project:
    name: Standard API project
    uses: nimblehq/elixir-templates/.github/workflows/reusable_phoenix_project.yml@composite_2.0
    with:
      new_project_options: "--no-html --no-webpack"
      variant: "api"

  non-standard_api_project:
    name: Non-Standard API project
    uses: nimblehq/elixir-templates/.github/workflows/reusable_phoenix_project.yml@composite_2.0
    with:
      new_project_options: "--no-html --no-webpack --module=SampleCustomModule --app=sample_custom_app"
      variant: "api"

  standard_web_project:
    name: Standard Web project
    uses: nimblehq/elixir-templates/.github/workflows/reusable_phoenix_project.yml@composite_2.0
    with:
      new_project_options: ""
      variant: "api"

  non-standard_web_project:
    name: Non-Standard Web project
    uses: nimblehq/elixir-templates/.github/workflows/reusable_phoenix_project.yml@composite_2.0
    with:
      new_project_options: "--module=SampleCustomModule --app=sample_custom_app"
      variant: "api"
