name: "CI Tests"
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    container: elixir:1.10-alpine
    services:
      db:
        image: postgres:11-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Update container
      run: |
        apk update
        apk add build-base
        mix local.rebar --force
        mix local.hex --force

    - name: Install Dependencies
      run: mix deps.get

    - name: Create database
      run: mix ecto.create
      env:
        MIX_ENV: test
        DB_HOST: db

    - name: Migrate database
      run: mix ecto.migrate
      env:
        MIX_ENV: test
        DB_HOST: db

    - name: Run lint
      run: mix lint
      
    - name: Run Tests
      run: mix test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MIX_ENV: test
        DB_HOST: db