name: Publish Wiki

on:
  push:
    branches:
      - develop
      - chore/add-template-development-docs
    paths:
      - .github/wiki/**

jobs:
  publish:
    name: Publish Wiki
    uses: nimblehq/github-actions-workflows/.github/workflows/publish_wiki.yml@e42052106789014fb1f8b722ab02abe4390e3e1d
    with:
      USER_NAME: github-wiki-action
      USER_EMAIL: dev@nimblehq.co
    secrets:
      USER_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }}
