name: Publish Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - develop
      - chore/add-template-development-docs

jobs:
  publish:
    - name: Publish Wiki
      uses: https://github.com/nimblehq/github-actions-workflows/blob/develop/.github/workflows/publish_wiki.yml@0.1.0
      with:
        USER_NAME: github-wiki-action
        USER_EMAIL: dev@nimblehq.co
      secrets:
        USER_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }}
