name: Publish to Hex package manager

on:
  workflow_run:
    workflows:
      - Test template
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    name: Publish hex package

    runs-on: ubuntu-latest
    
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Install .tool-versions.
        uses: asdf-vm/actions/install@v1

      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Publish to Hex.pm
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
