name: "Test Live variant on custom LiveView project"

on: push

env:
  OTP_VERSION: 23.2.1
  ELIXIR_VERSION: 1.11.3
  PHOENIX_VERSION: 1.5.7
  NODE_VERSION: 14

jobs:   
  unit_test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:12.3
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
        
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
             
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=yarn_cache_dir::$(yarn cache dir)"
      
      - name: npm packages cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.yarn_cache_dir }}
            **/yarn.lock
            **/node_modules
          key: ${{ runner.os }}-npm-packages-${{ hashFiles('**/package.json*') }}
          restore-keys: |
            ${{ runner.os }}-npm-packages-
              
      - uses: nimblehq/elixir-templates@composite_1.1
        with:
          new_project_options: '--live --module=CustomModule --app=custom_app'
          variant: 'live'
